server:
  port: 8000

spring:
  application:
    name: rococo-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  grpc:
    client:
      channels:
        rococo-museum:
          address: 'static://localhost:9096'
          negotiation-type: plaintext
        rococo-artist:
          address: 'static://localhost:9095'
          negotiation-type: plaintext
        rococo-painting:
          address: 'static://localhost:9097'
          negotiation-type: plaintext
        rococo-userdata:
          address: 'static://localhost:9094'
          negotiation-type: plaintext

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.grpc: DEBUG
    guru.qa.rococo.service.GrpcClientLoggerInterceptor: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
---